### ISSUE TITLE
Voted delegates not showing with message none voted for

### ISSUE THREAD

**Issue by 2mdoty** [LiskHQ/lisk-ui#39] opened 2016-05-07 23:18 UTC
Have to reload web client page and log back in to see delegates voted for after returning from sleep mode, just get message i haven't voted for any delegates otherwise even though it shows number voted for at top.

Firefox 45.0.2, Windows 7

**Comment by fix** [comment] 2016-08-30 10:24
closing it because it needs reproduction

**Closed** 2016-08-30 10:24 UTC
Labels: bug
