### ISSUE TITLE
Uncaught IndexSizeError: Failed to execute 'arc' on 'CanvasRenderingContext2D'

### ISSUE THREAD

**Issue by karmacoma** [LiskHQ/lisk-ui#3] opened 2016-01-29 17:12 UTC
Encountering the following in the dev console:

```
Uncaught IndexSizeError: Failed to execute 'arc' on 'CanvasRenderingContext2D': The radius provided (-0.5) is negative.
```

**Comment by mrv777** [comment] 2016-05-18 13:39
Not sure if this is still an issue.  Couldn't reproduce here.
Best guess is that it seems Chart.js defaults to:
` -0.5 * Math.PI `
Not sure if there is, or was, as issue with Math.PI
http://www.chartjs.org/docs/#doughnut-pie-chart-data-structure

**Comment by fix** [comment] 2016-08-30 10:22
i got this error regularly, i think this is angular-material issue

**Comment by fix** [comment] 2016-08-30 10:23
closing it as won't fix. Please @karmacoma reopen if you think i am wrong.

**Closed** 2016-08-30 10:23 UTC
Labels: bug, wontfix
